package:
    name: "chronos-textgen"
    version: "1.0.0"

source:
    git-url: https://github.com/SciMind2460/chronos

build:
    number: 0
    script: |
        python setup.py install
        # Install pip dependencies
        pip install torch

requirements:
    host:
        - python=3.12  # Specify your desired Python version
        - setuptools
    build:
        - python=3.12
        run: 
        - python=3.12
        - transformers
        - inflect
        - pytorch 
        - numpy=1.26.*

about:
    home: https://github.com/SciMind2460/chronos
    license: MIT
    license-family: MIT
    license-file: LICENSE
    summary: "A small AI model that can be used in Python packages through pip and git+ and conda."

extra:
    recipe-maintainers:
        - SciMind2460

